### ISSUE TITLE
Instance 개발 상황 Follow Up

### ISSUE THREAD

**Issue by KyumKyum** [PROJECT-HOLME/HOLME_MATTER_INS#4]
부득이하게 개발 진행을 이번주 목요일 (10/26)까지 개발 진행이 어려울 것 같습니다. @Hyuktae-Kwon 여기에 개발 진행상황을 간략하게 적어서 제가 나중에 Follow-up할 수 있도록 해주시면 감사하겠습니다.

**Comment by Hyuktae-Kwon** [comment]
아스키아트들 색깔 수정 완료

**Comment by Hyuktae-Kwon** [comment]
모든 인스턴스들 하이브마인드와 연결 완료

**Comment by KyumKyum** [comment]
확인!
